### PR TITLE
added directory index

### PR DESCRIPTION
**Pull request by bashaus**
added ability to define a directory index, a base directory and configure the target property

can turn paths from `/blog/index.html` into `/blog/`.

### CODE REVIEW

**Comment by greduan** [comment]
So what does this actually achieve? Does it make `/blog/index.html` into `/blog/` only when the file is `index.html`? Or does it do it with every file?

What are the advantages of this over something else?

Sorry I haven't used Metalsmith in a long while.

**Comment by bashaus** [comment]
So I was looking in to metalsmith-paths for use on a static site generator. At the moment, the `href` functionality is inconsistent because the filename (basename and extension) is never passed through with href. So the `href`property for `/blog/file.ext` is the same as `/blog/index.html` - both are `/blog/`  

The purpose of this change is to put the filename in to the href, except only when the basename matches the value of `directoryIndex`. This helps with SEO so that pages which are `index.html` aren't linked as such - they just have the directory name.

**Comment by bashaus** [comment]
Check out the diff for the tests for a practical example. You will also probably need to increase the version number as this introduces an API change.

**Comment by bashaus** [comment]
Are the moment, the `path` property will give the full URL (including filename). This changes the behaviour by dropping the basename if it matches the directory index, helping with SEO

**Comment by greduan** [comment]
Is it possible to introduce this change without an API change?

**Comment by bashaus** [comment]
It's a backwards compatible change - so older implementations will continue to work if that's what you're worried about.

**Comment by bashaus** [comment]
The code requires you to explicitly turn it on to use it.

**Comment by greduan** [comment]
Yeah that was my question. Looks good. Thanks for the pull. :)

**Pull request merged**
